import { Key, Mod } from './enums'

export const symbols: Record<string, string> = {
	'left_control': '⌃',
	'left_option': '⌥',
	'left_command': '⌘',
	'left_shift': '⇪',
	'right_control': '⌃',
	'right_option': '⌥',
	'right_command': '⌘',
	'right_shift': '⇪',
	'fn': '🌐',
	'caps_lock': 'caps',
	'tab': '⇥',
	'spacebar': '␣',
	'return_or_enter': '⏎',
	'escape': '⎋',
	'delete_or_backspace': 'bsp',
	'delete_forward': 'del',
	'up_arrow': '↑',
	'down_arrow': '↓',
	'left_arrow': '←',
	'right_arrow': '→',
	'page_up': '⇞',
	'page_down': '⇟',
	'home': 'home',
	'end': 'end',
	'grave_accent_and_tilde': '`',
	'hyphen': '-',
	'equal_sign': '=',
	'open_bracket': '[',
	'close_bracket': ']',
	'backslash': '\\',
	'semicolon': ';',
	'quote': "'",
	'comma': ',',
	'period': '.',
	'slash': '/',
	'volume_increment': '🔊',
	'volume_decrement': '🔉',
	'mute': '🔇',
	'play_or_pause': '⏯️',
	'fastforward': '⏭️',
	'rewind': '⏮️',
	'brightness_increment': '☀️',
	'brightness_decrement': '🌙',
	'f1': 'F1',
	'f2': 'F2',
	'f3': 'F3',
	'f4': 'F4',
	'f5': 'F5',
	'f6': 'F6',
	'f7': 'F7',
	'f8': 'F8',
	'f9': 'F9',
	'f10': 'F10',
	'f11': 'F11',
	'f12': 'F12'
}

export function icon(key: Key | Mod | string): string {
	const keyStr = typeof key == 'string' ? key : String(key)
	return symbols[keyStr] || keyStr
}
